{% set name = "mlipx" %}
{% set version = "0.1.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlipx-{{ version }}.tar.gz
  sha256: f5b6b8a244fe62c23c347f42383b017f5d90769ff89d40569a6639c2ab43d0a8

build:
  entry_points:
    - mlipx = mlipx.cli.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - dvc-s3 >=3.2.0
    - mp-api >=0.45.3
    - mpcontribs-client >=5.10.2
    - rdkit2ase >=0.1.4
    - python >={{ python_min }},<4.0
    - zntrack >=0.8.5
    - ase >=3.24.0
    - typer >=0.15.1
    - plotly >=6.0.0
    - zndraw >=0.5.10
    - znh5md >=0.4.4
    - lazy-loader >=0.4
    - platformdirs 3.10

test:
  imports:
    - mlipx
  commands:
    - pip check
    - mlipx --help
  requires:
    - pip
    - git
    - python {{ python_min }}

about:
  home: https://github.com/basf/mlipx
  summary: Machine-Learned Interatomic Potential eXploration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
