{% set name = "mlipx" %}
{% set version = "0.1.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlipx-{{ version }}.tar.gz
  sha256: 3c70a0e6f921c420f3612e3aed7a8c5a125d18b7d8339fed9c8a98fc90f33c9e

build:
  entry_points:
    - mlipx = mlipx.cli.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - zntrack 0.8.0
    - ase >=3.0.0,<4.0.0
    - typer >=0.13.0,<0.14.0
    - plotly >=5.0.0,<6.0.0
    - zndraw >=0.5.2,<0.6.0
    - znh5md >=0.3.6,<0.4.0
    - lazy-loader >=0.4.0,<0.5.0
    - platformdirs 3.10

test:
  imports:
    - mlipx
  commands:
    - pip check
    - mlipx --help
  requires:
    - pip
    - git
    - python {{ python_min }}

about:
  home: https://github.com/basf/mlipx
  summary: Machine-Learned Interatomic Potential eXploration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
