{% set name = "mlipx" %}
{% set version = "0.1.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlipx-{{ version }}.tar.gz
  sha256: 1a0dbe96a7d0b85f40a0ac8f5f8d9eb163e6e32983114f0030106c2f539f3895

build:
  entry_points:
    - mlipx = mlipx.cli.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - pydantic >=2.10.6
    - dvc-s3 >=3.2.0
    - mp-api >=0.45.3
    - mpcontribs-client >=5.10.2
    - rdkit2ase >=0.1.4
    - python >={{ python_min }},<4.0
    - zntrack >=0.8.5
    - ase >=3.24.0
    - typer >=0.15.1
    - plotly >=6.0.0
    - zndraw >=0.5.10
    - znh5md >=0.4.4
    - lazy-loader >=0.4
    - platformdirs 3.10

test:
  imports:
    - mlipx
  commands:
    - pip check
    - mlipx --help
  requires:
    - pip
    - git
    - python {{ python_min }}

about:
  home: https://github.com/basf/mlipx
  summary: Machine-Learned Interatomic Potential eXploration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
